### ISSUE TITLE
PyPi version available?

### ISSUE THREAD

**Issue by imann24** [IgniparousTempest/puffadder#2]
Hi, thanks for putting this together. Curious if there is a version available in a public Python registry?

**Comment by IgniparousTempest** [comment]
Hi there is, at [PyPi](https://pypi.org/project/puffadder/). Although project has pretty much been bested by Python's [dataclasses](https://docs.python.org/3/library/dataclasses.html) introduced in 3.7. You could still use this for older python versions, but for newer ones use a dataclass.

**Comment by imann24** [comment]
🙏 cheers! Thanks for the references. 
<hr>

Clearly the standard lib needs to get on your level and add SEO for when I search `python lombok`
